# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db215f19144a5425ae8f7b34852ec3d2e482a044a9657742057589a1c9a5b47f4558b514d66d7807d8f5c4b2f35d4e8060cb3a8cddfa0dd45e7c87cce6be3e5f

test:
  secret_key_base: a905807d2ab827fa44398eed9008dda42d890d4eeb480f2a346fcfcebc82c3f0e6e37a6c48ce12e99af87cb6b0448062aa6062f68f0b28c2619db20c48cd733d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
